<%@ page import="java.math.BigInteger, java.security.*"%>
<html>
<head>
	<title>Result</title>
</head>
<body style="margin-top: 200px; font-size: 38px;">
<center>
<%
	String password = "21232f297a57a5a743894a0e4a801fc3"; //Equivalent of "admin"
	String id = request.getParameter("id");
	String s = request.getParameter("password");

	if(id.equals("admin"))
	{
		try {
			//MD5 Hashing
			MessageDigest md = MessageDigest.getInstance("MD5");
			byte[] messageDigest = md.digest(s.getBytes());
			BigInteger no = new BigInteger(1, messageDigest);
			String hashtext = no.toString(16);
			while (hashtext.length() < 32) 
			{
				hashtext = "0" + hashtext;
			}
			//Auth	
			out.println("Stored MD5 hash for admin user: "+ password);%>
			<br><br>
			<%
			out.println("HashCode Generated by MD5 for Entered password: " + hashtext);%>
			<br><br>
			<%
			out.println("Action: ");	
			if(hashtext.equals(password))
			{
				out.println("Admin user authenticated");
			}
			else
			{
				out.println("Invalid credentials");
			}
		}
		catch (NoSuchAlgorithmException e) 
		{
			throw new RuntimeException(e);
		}

	}
	else
	{
		out.println("Invalid username.");
	%><br><br>
	<%
		out.println("Try 'admin' as username");
	}
%>

	
</center>
</body>
</html>